[package]
name = "bevy_easings"
version = "0.1.0"
authors = ["Fran√ßois Mockers <mockersf@gmail.com>"]
edition = "2018"
description = "Easing plugin for Bevy"
repository = "https://github.com/mockersf/bevy_extra"
homepage = "https://github.com/mockersf/bevy_extra/tree/master/bevy_easings"
documentation = "https://docs.rs/bevy_easings"
keywords = ["bevy", "animation", "easing"]
license = "MIT"
readme = "README.md"

[dependencies]
bevy = "0.2"
interpolation = "0.2"
rand = "0.7"

[features]
default = [ "ease_handle" ]
ease_handle = []
