[package]
name = "bevy_log_diagnostic"
version = "0.1.0"
authors = ["FrancÌ§ois Mockers <mockersf@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.2.1"
tracing = "0.1"
